### ISSUE TITLE
What is the best way to generate flow-type definitions for TypeScript projects?

### ISSUE THREAD

**Issue by IjzerenHein** [react-native-community/bob#10]
This is a question/discussion/feature request around flow type definitions.
Currently when you write your project using TypeScript, it doesn't seem possible to generate flow-type definitions from that source using Bob. This is an inconvenience, as many app-projects use flow and the maintainer of the lib ideally doesn't want to maintain separate flow type definitions when writing the lib TypeScript.

My question here is, is the above assumption correct, and how do other lib maintainers deal with supporting flow-types?

Any insights are appreciated.

cheers, Hein

**Comment by satya164** [comment]
> it doesn't seem possible to generate flow-type definitions from that source using Bob

There's no reliable tool exists to do that. Otherwise we'd add it to bob.

You might wanna check https://github.com/bcherny/flow-to-typescript, but you'll most probably need to edit the generated definitions to actually make them work.

> how do other lib maintainers deal with supporting flow-types

Personally I don't. Flow isn't very friendly to lib authors and usually the definitions break quite often. Let the community maintain the definitions if they need.

**Comment by IjzerenHein** [comment]
Alright, thank you so much for the insight @satya164 !

I personally still want to support flow for my libs, as I'm a consumer of them myself. In case I have a good strategy/best practise (preferably automated but I guess that's not gonne happen anytime soon), I will drop it here for review.

Thanks!
