### ISSUE TITLE
Can I use CocoaPods while using Swift to build native module?

### ISSUE THREAD

**Issue by SunskyXH** [react-native-community/bob#24]
# Question
Just as the title says, if my swift code is using other third-party pods, and I initialized `Podfile` with command  `pods init`.Then the compiler told me that it couldn't find `React/RCTBridgeModule.h`. So I have to add all of these react-native pods into `Podfile`, and now it looks like this below:

<details>
<summary>Podfile</summary>

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'MyNavtiveModule' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for JikeSdk
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # some 3rd party pod here
end

</details>

I think this could not be the best practice. What can I do to improve my `Podfile`?

**Comment by ManAnRuck** [comment]
+1
have the same issue 👨‍💻

**Comment by satya164** [comment]
I believe this adds proper template for swift https://github.com/react-native-community/bob/commit/ed0289ec47dbaea73ef41f7d4562e14ad301600e

**Comment by shamilovtim** [comment]
@satya164 

This is not resolved. I initialized a Swift example just as instructed and hit this exact error.

**Comment by CapiPato** [comment]
> @satya164
> 
> This is not resolved. I initialized a Swift example just as instructed and hit this exact error.
> 
> 'React/RCTBridgeModule.h' file not found

Did you fix this problem?

**Comment by TheNoim** [comment]
Yeah, hit the same error. Really annoying. Why does this template exist if it isn't working?

**Comment by magouyaware** [comment]
I know this is closed, but for anyone else that runs into this issue in the future, I found some helpful information here, especially if you are on React Native 0.68 or newer:
https://stackoverflow.com/a/73189981

Basically, you can delete all the manual pod declarations related to react native and replace it with two lines. There is now a script that will add the pods you need for you:
```
# Put this at the top of your Podfile
require_relative '../node_modules/react-native/scripts/react_native_pods'

# Put this right before your target declaration
use_react_native!
target 'some-xcode-target' do
# Add project-specific target setup like dependencies
end
```

@satya164 To answer your question in [this issue](https://github.com/callstack/react-native-builder-bob/issues/32#issuecomment-603437525) (which I think is also relevant in this case):

> Why isn't building the example enough for you? What do you expect to do with the build of the library alone if it's not running in a React Native app?

As a developer of a native module, I want to run unit tests and CI builds of JUST the native module. Relying on an example app to be able to build my native module is really bad practice. If my example app fails, then there could be other issues that cause that failure that have nothing to do with my native module. Being able to build the native module separately helps me determine the source of my problem... If the module builds but the example app doesn't then I KNOW the problem is in the module and I can start looking there. Likewise, if my module doesn't build then I immediately know where to start looking for the problem.
