### ISSUE TITLE
Is it possible to support multiple source folders?

### ISSUE THREAD

**Issue by MichaelPeterJoyce** [react-native-community/bob#33]
# Feature Request

It would be great if the configuration could support multiple source folders

I have a lerna monorepo from this i build a react native component and a react web component that i use on an internal NPM repository. 

As part of this lerna monorepo i have a shared logic folder that all API requests and typescript models etc so the folder structure is like so

Packages
      -> shared
      -> native
      -> web

The web project is fine because i build with webpack and it is able to resolve and bundle the imports from shared.

But using bob i cannot import and the components from shared because it doesn't automatically bundle these files

Something like this being able to add multiple source folders?

`  "@react-native-community/bob": {
    "source": ["src", "../shared/src"],
    "output": "lib",
    "targets": [
      "commonjs",
      "module",
      "typescript"
    ]
  },
`
Thanks very much for your time

**Comment by satya164** [comment]
For monorepos, you can add bob in the `prepare` script for each package that needs it.

> But using bob i cannot import and the components from shared because it doesn't automatically bundle these files

For development, you should configure metro and alias the package to use the source files using babel-plugin-module-resolver like you do with webpack instead of having to build them each time.

Example https://github.com/react-navigation/react-navigation

**Comment by sanketsahu** [comment]
@satya164 Would this library ever support the scaffolding of a monorepo? Is that on the roadmap?
