### ISSUE TITLE
Is there support for import aliases?

### ISSUE THREAD

**Issue by CarlosBalladares** [react-native-community/bob#56]
# Question
Is there support for import aliases?

For example in some files I have
``` javascript
import {SomeEnum} from "@/enums";
// ...
```
My ts config supports aliases, however bob doesn't resolve these in the final built version of my library.
I tried adding a babel config, this didn't work either. Is this currently supported?

**Comment by satya164** [comment]
You can specify your own babel config if you pass `configFile: true`: https://github.com/react-native-community/bob#commonjs

However, TypeScript doesn't compile path aliases. In TS, the alias feature is intended to reflect the runtime behavior, not to change the runtime behavior. So the delcaration files generated by typescript will have what you've typed instead of the alias result.

So basically if you're writing a library which will publish declaration files, you shouldn't use path aliases. Only use them in apps.
