### ISSUE TITLE
Adding an external dependency on the module - Android

### ISSUE THREAD

**Issue by TfADrama** [react-native-community/bob#63]
Hi
I want my react native module to import a SDK as a dependency.
In iOS it's already working, but i have little experience with android.

Im my react native module _**buidle.gradle**_ i added the following repo inside the repositories object.

```
maven {
    url "s3://repo.pagesuite.com/android/"
    credentials(AwsCredentials) {
      accessKey = ""
      secretKey = ""
    }
 }
```

On the same file i added the following import to the dependencies object.

```
implementation "repo.android.pagesuite.com:psReaderSdkForClients:0.48"
```

After this, i compile the project and i see the dependencies on the external libraries and i actually can use the SDK.

The problem is, **when i compile the example project** it throws a dependency error:
```
Could not find repo.android.pagesuite.com:psReaderSdkForClients:0.48.

Searched in the following locations:
  - file:/Users/user/.m2/repository/repo/android/pagesuite/com/psReaderSdkForClients/0.48/psReaderSdkForClients-0.48.pom
  - file:/Users/user/Documents/PageSuite/project/react-native-pagesuite/example/node_modules/react-native/android/repo/android/pagesuite/com/psReaderSdkForClients/0.48/psReaderSdkForClients-0.48.pom
  - file:/Users/user/Documents/PageSuite/project/react-native-pagesuite/example/node_modules/jsc-android/dist/repo/android/pagesuite/com/psReaderSdkForClients/0.48/psReaderSdkForClients-0.48.pom
  - https://dl.google.com/dl/android/maven2/repo/android/pagesuite/com/psReaderSdkForClients/0.48/psReaderSdkForClients-0.48.pom
  - https://jcenter.bintray.com/repo/android/pagesuite/com/psReaderSdkForClients/0.48/psReaderSdkForClients-0.48.pom
  - https://www.jitpack.io/repo/android/pagesuite/com/psReaderSdkForClients/0.48/psReaderSdkForClients-0.48.pom
Required by:
    project :app > project :reactnativepagesuite
```

The dependency appears on the external libraries too. What am i missing?

**Comment by chj-damon** [comment]
same to me.

**Comment by Krizzu** [comment]
let's keep this documentation-related issue in one place [here](https://github.com/react-native-community/bob/issues/89)

**Comment by Krizzu** [comment]
@TfADrama 

What about adding maven to the root `build.gradle`'s `repositories` ?

Are you sure if the url is correct one?

**Comment by TfADrama** [comment]
> @TfADrama
> 
> What about adding maven to the root `build.gradle`'s `repositories` ?
> 
> Are you sure if the url is correct one?

Creating a lib with bob builder only creates one build gradle file, what are you talking about? Of course the maven is there, it's the only place to put it.

The URL is obviously working, didn't you read my post? It works when i also import from the consuming project...

**Comment by satya164** [comment]
@TfADrama maybe you'll have better luck getting answers if you're not rude to people trying to help you. it's a Open Source library that you use for free. maintainers try to help because they want to, nobody owes you anything. if you wanna improve docs and other people then you can send PRs or have friendly conversations.

**Comment by TfADrama** [comment]
> @TfADrama maybe you'll have better luck getting answers if you're not rude to people trying to help you. it's a Open Source library that you use for free. maintainers try to help because they want to, nobody owes you anything. if you wanna improve docs and help other people then you can send PRs or have friendly conversations.

@satya164 
No, i dont agree.
Thats the defence card you always pull. But in this case, i just dont agree.
I opened an issue, than its closed by referencing another issue that doesn't relate at all. I was like, okey, maybe i am missing something, maybe im just dumb. I didnt say anything. After almost one year, i replied just to see what happens, and then the same person doesn't at least read the post? again? Then it calls me stupid in between lines? just no. I prefer to be honest and direct than friendly like i as a dumb kid that doesn't even know what this framework is for.

You can do whatever you want with your lib, you are right, its open source, its yours, congrats to you. But i can sleep at night at least for this time. 
I know you dont care for my opinion, and i don't care or agree with yours.

**Comment by satya164** [comment]
Thanks so much for your appreciation for a l tool we built entirely in our free time to help other people. Oh, what? We didn't manage to solve one issue you had in our free time even though we still built all this stuff to help others and didn't ask anything in return? Ah, all of that is irrelevant because we didn't manage to help your issue without even a appreciation. I see.

**Comment by Krizzu** [comment]
Look, I tried to help you, even if your issue is **not** related with `bob` directly. If your intent is to fight back anyone who does, then I would not to get any help.

> The URL is obviously working, didn't you read my post? 

I did read your post. I asked to check it, because it's a common human error to make mistakes here.

> Creating a lib with bob builder only creates one build gradle file, what are you talking about? Of course the maven is there, it's the only place to put it.

You see, you said you have the problem **in a context of the example project**. I assumed you're talking about `bob`'s example project, [hence I asked you to try to place maven url in top level build.gradle](https://github.com/callstack/react-native-builder-bob/blob/main/packages/create-react-native-library/templates/example/example/android/build.gradle#L23)

> I opened an issue, than its closed by referencing another issue that doesn't relate at all

It might looks like it's not related, but they're actually associated with consuming external dependencies. It's easier for us to have all info in one ticket, than having multiple scattered. And, like I already said, this type of problem is not related to `bob` directly, but we try to help anyway, by providing documentation/answering issues.

> Then it calls me stupid in between lines? 

Not my intention.

Anyway, I support Satya in everything he said.
