### ISSUE TITLE
Is it possible to have the cli watch for files changes and rebuild?

### ISSUE THREAD

**Issue by cmaycumber** [react-native-community/bob#81]
# Question

Is it possible to create a configuration that allows bob to run the ```$ bob build``` when the src files change? 

I know a lot of cli's have a ```watch``` command specifically but it doesn't seem that bob has one. 

This would be super helpful because I'm running bob with yarn workspaces and it would allow for the package to rebuild without me manually having to re-run the prepare script whenever a change is saved.

**Comment by satya164** [comment]
I'd suggest to use the source files for development instead of compiling. The project generated by bob configures this by default, for monorepos, you can refer React Navigation's repo for inspiration https://github.com/react-navigation/react-navigation

If you'd still like to compile files, I guess you could use one of the watcher packages such as `nodemon`
